// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListBuckets() {
  return window['go']['app']['App']['ListBuckets']();
}

export function LoadLatestLoginInfo() {
  return window['go']['app']['App']['LoadLatestLoginInfo']();
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}

export function GetObject(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetObject'](arg1, arg2, arg3);
}

export function ListAllLoginInfo() {
  return window['go']['app']['App']['ListAllLoginInfo']();
}

export function DeleteObject(arg1, arg2) {
  return window['go']['app']['App']['DeleteObject'](arg1, arg2);
}

export function ListObjects(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListObjects'](arg1, arg2, arg3, arg4);
}

export function MakeBucket(arg1) {
  return window['go']['app']['App']['MakeBucket'](arg1);
}

export function CheckDbError() {
  return window['go']['app']['App']['CheckDbError']();
}

export function DeleteBucket(arg1) {
  return window['go']['app']['App']['DeleteBucket'](arg1);
}
