// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {app} from '../models';
import {db} from '../models';

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function CheckDbError():Promise<string>;

export function DeleteBucket(arg1:string):Promise<string>;

export function DeleteObject(arg1:string,arg2:string):Promise<app.ObjectHandlerResult>;

export function DoPutObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<app.ObjectHandlerResult>;

export function GetObject(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<app.ObjectHandlerResult>;

export function ListAllLoginInfo():Promise<Array<db.LoginInfo>>;

export function ListBuckets():Promise<app.ListBucketResult>;

export function ListObjects(arg1:string,arg2:string,arg3:string,arg4:number):Promise<app.ListObjectResult>;

export function LoadLatestLoginInfo():Promise<db.LoginInfo>;

export function Login(arg1:db.LoginInfo,arg2:boolean):Promise<string>;

export function MakeBucket(arg1:string):Promise<string>;

export function PutObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<app.ObjectHandlerResult>;

export function SelectFiles(arg1:string):Promise<app.SelectFilesResult>;
