// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDbError() {
  return window['go']['app']['App']['CheckDbError']();
}

export function ListAllLoginInfo() {
  return window['go']['app']['App']['ListAllLoginInfo']();
}

export function LoadLatestLoginInfo() {
  return window['go']['app']['App']['LoadLatestLoginInfo']();
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}
