// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {app} from '../models';

export function CheckDbError():Promise<string>;

export function DeleteBucket(arg1:string):Promise<string>;

export function DeleteObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<models.ErrResult>;

export function DeleteObjects(arg1:string,arg2:Array<app.DeleteKey>,arg3:string,arg4:string):Promise<models.ErrResult>;

export function DoGetObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:boolean):Promise<models.ErrResult>;

export function DoPutObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.ErrResult>;

export function GetAccountId():Promise<string>;

export function GetBucketDetailResult(arg1:string):Promise<models.GetBucketVersioningResult>;

export function ListAllLoginInfo():Promise<Array<models.LoginInfo>>;

export function ListBuckets():Promise<models.ListBucketsResult>;

export function ListObjectVersions(arg1:string,arg2:string):Promise<models.GetObjectVersionsResult>;

export function ListObjects(arg1:string,arg2:string,arg3:string,arg4:number):Promise<models.ListObjectResult>;

export function ListenListObjectsEvent():Promise<void>;

export function LoadAllDownloadTasks():Promise<Array<models.DownloadTask>>;

export function LoadAllUploadTasks():Promise<Array<models.UploadTask>>;

export function LoadLatestLoginInfo():Promise<models.LoginInfo>;

export function LoadSettings():Promise<models.Settings>;

export function Login(arg1:models.LoginInfo,arg2:boolean,arg3:boolean):Promise<string>;

export function Logout():Promise<void>;

export function MakeBucket(arg1:string):Promise<string>;

export function PutBucketVersioning(arg1:string,arg2:string):Promise<string>;

export function PutDir(arg1:string,arg2:string,arg3:string):Promise<models.ErrResult>;

export function RemoveDownloadTask(arg1:models.DownloadTask):Promise<models.ErrResult>;

export function RemoveUploadTask(arg1:models.UploadTask):Promise<models.ErrResult>;

export function ResumeDownloadTask(arg1:models.DownloadTask):Promise<models.ErrResult>;

export function ResumeUploadTask(arg1:models.UploadTask):Promise<models.ErrResult>;

export function SelectDownloadPath():Promise<models.SelectDownloadPathResult>;

export function SelectUploadFiles(arg1:string,arg2:string):Promise<models.ErrResult>;

export function SelectUploadFolder(arg1:string,arg2:string):Promise<models.ErrResult>;

export function UpdateSettings(arg1:models.Settings):Promise<models.ErrResult>;
