// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {db} from '../models';

export function CheckDbError():Promise<string>;

export function DeleteBucket(arg1:string):Promise<string>;

export function DeleteObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<app.ObjectHandlerResult>;

export function DeleteObjects(arg1:string,arg2:Array<app.DeleteKey>,arg3:string,arg4:string):Promise<app.ObjectHandlerResult>;

export function DoGetObject(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:boolean):Promise<app.ObjectHandlerResult>;

export function DoPutObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<app.ObjectHandlerResult>;

export function DoUploadFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListAllLoginInfo():Promise<Array<db.LoginInfo>>;

export function ListBuckets():Promise<app.ListBucketResult>;

export function ListObjects(arg1:string,arg2:string,arg3:string,arg4:number):Promise<app.ListObjectResult>;

export function LoadAllDownloadTasks():Promise<Array<db.DownloadTask>>;

export function LoadAllUploadTasks():Promise<Array<db.UploadTask>>;

export function LoadLatestLoginInfo():Promise<db.LoginInfo>;

export function LoadSettings():Promise<db.Settings>;

export function Login(arg1:db.LoginInfo,arg2:boolean,arg3:boolean):Promise<string>;

export function Logout():Promise<void>;

export function MakeBucket(arg1:string):Promise<string>;

export function PutDir(arg1:string,arg2:string,arg3:string):Promise<app.ObjectHandlerResult>;

export function RemoveDownloadTask(arg1:db.DownloadTask):Promise<app.ObjectHandlerResult>;

export function RemoveUploadTask(arg1:db.UploadTask):Promise<app.ObjectHandlerResult>;

export function ResumeDownloadTask(arg1:db.DownloadTask):Promise<app.ObjectHandlerResult>;

export function ResumeUploadTask(arg1:db.UploadTask):Promise<app.ObjectHandlerResult>;

export function SelectDownloadPath():Promise<app.SelectDownloadPathResult>;

export function SelectUploadFiles(arg1:string):Promise<app.SelectUploadFilesResult>;

export function SelectUploadFolder():Promise<app.SelectUploadFolderResult>;

export function SetupMenu():Promise<void>;

export function UpdateSettings(arg1:db.Settings):Promise<app.ObjectHandlerResult>;
