// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeforeClose(arg1) {
  return window['go']['app']['App']['BeforeClose'](arg1);
}

export function CheckDbError() {
  return window['go']['app']['App']['CheckDbError']();
}

export function DeleteBucket(arg1) {
  return window['go']['app']['App']['DeleteBucket'](arg1);
}

export function DeleteObject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['DeleteObject'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteObjects(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteObjects'](arg1, arg2, arg3, arg4);
}

export function DoPutObject(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DoPutObject'](arg1, arg2, arg3, arg4);
}

export function GetObject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetObject'](arg1, arg2, arg3, arg4, arg5);
}

export function ListAllLoginInfo() {
  return window['go']['app']['App']['ListAllLoginInfo']();
}

export function ListBuckets() {
  return window['go']['app']['App']['ListBuckets']();
}

export function ListObjects(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListObjects'](arg1, arg2, arg3, arg4);
}

export function LoadAllUploadTasks() {
  return window['go']['app']['App']['LoadAllUploadTasks']();
}

export function LoadLatestLoginInfo() {
  return window['go']['app']['App']['LoadLatestLoginInfo']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['app']['App']['Login'](arg1, arg2, arg3);
}

export function MakeBucket(arg1) {
  return window['go']['app']['App']['MakeBucket'](arg1);
}

export function PutDir(arg1, arg2, arg3) {
  return window['go']['app']['App']['PutDir'](arg1, arg2, arg3);
}

export function RemoveUploadTask(arg1) {
  return window['go']['app']['App']['RemoveUploadTask'](arg1);
}

export function ResumeUploadTask(arg1) {
  return window['go']['app']['App']['ResumeUploadTask'](arg1);
}

export function SelectDownloadPath() {
  return window['go']['app']['App']['SelectDownloadPath']();
}

export function SelectUploadFiles(arg1) {
  return window['go']['app']['App']['SelectUploadFiles'](arg1);
}

export function SetupMenu() {
  return window['go']['app']['App']['SetupMenu']();
}
